### ISSUE TITLE
expandIgnoringCase looks broken

### ISSUE THREAD

**Issue by cameron** [elm-scotland/elm-tries#1]
It's late and I'm beat — please forgive the terse report! And thanks for the lib. 

![Screen Shot 2020-06-14 at 4 04 00 AM](https://user-images.githubusercontent.com/149910/84591549-1f7afa00-adf4-11ea-83aa-02cdcb24efbf.png)

**Comment by cameron** [comment]
Also seems like that function is missing a test!

**Comment by rupertlssmith** [comment]
Yes, the algorithm is garbage and there is no test. I've created this branch to develop a fix: 

https://github.com/elm-scotland/elm-tries/tree/expand-ignore-case

**Comment by rupertlssmith** [comment]
Published this fix with a new version of the package 1.0.1.
